#!/usr/bin/env bash
# Dev Container git signing helper.
#
# Typical setup: configure git on the *host*:
#   git config --global user.name "…"
#   git config --global user.email "…"
#   git config --global gpg.format ssh
#   git config --global user.signingkey "key::ssh-ed25519 AAAA…"
#   git config --global commit.gpgsign true
# Cursor/VS Code copies ~/.gitconfig into the container.
#
# This script only:
#   1. Refuses to touch Cursor Cloud HSM wiring
#   2. Ensures an SSH agent socket is available (private key stays on the host)
#   3. Writes Dev Container–only tweaks to ~/.config/bookclerk/gitconfig via
#      include.path (does not rewrite the copied host gitconfig wholesale)
#   4. Optionally applies GIT_* / GIT_SSH_SIGNING_PUBKEY when set
#
# Cloud Agent Builds never run this (Dev Container postStart only). The shared
# Dockerfile and .cursor/cloud-agent-install.sh do not call git config.
set -euo pipefail

log() { printf 'devcontainer git-signing: %s\n' "$*"; }

# --- Cloud / HSM isolation -------------------------------------------------
if [[ "$(git config --global --get gpg.ssh.program 2>/dev/null || true)" == *cursor-git-ssh-keygen* ]]; then
  log "Cursor HSM gpg.ssh.program present; refusing to modify git config"
  exit 0
fi
if [[ -x /root/.cursor/bin/cursor-git-ssh-keygen && "${HOME:-}" == /root ]]; then
  log "Cloud Agent home detected; refusing to modify git config"
  exit 0
fi

BOOKCLERK_GIT_DIR="${HOME}/.config/bookclerk"
BOOKCLERK_GITCONFIG="${BOOKCLERK_GIT_DIR}/gitconfig"
BOOKCLERK_ENV="${BOOKCLERK_GIT_DIR}/agent.env"
mkdir -p "${BOOKCLERK_GIT_DIR}"

# --- Agent socket ----------------------------------------------------------
resolve_agent_sock() {
  local candidate
  for candidate in \
    "${SSH_AUTH_SOCK:-}" \
    /run/host-services/ssh-auth.sock \
    /tmp/host-ssh-agent.sock
  do
    [[ -n "${candidate}" && -S "${candidate}" ]] || continue
    if SSH_AUTH_SOCK="${candidate}" ssh-add -l >/dev/null 2>&1; then
      printf '%s\n' "${candidate}"
      return 0
    fi
    [[ -S "${candidate}" ]] || continue
    printf '%s\n' "${candidate}"
    return 0
  done
  return 1
}

sock="$(resolve_agent_sock || true)"
if [[ -z "${sock}" ]]; then
  log "no SSH agent socket; not enabling signing"
  log "host: eval \"\$(ssh-agent -s)\" && ssh-add ~/.ssh/<signing_key>, then reopen"
  exit 0
fi
export SSH_AUTH_SOCK="${sock}"

if ! ssh-add -l >/dev/null 2>&1; then
  log "agent at ${SSH_AUTH_SOCK} has no identities; not enabling signing"
  exit 0
fi

printf '%s\n' \
  "# Generated by .devcontainer/git-signing.sh" \
  "export SSH_AUTH_SOCK=$(printf '%q' "${SSH_AUTH_SOCK}")" >"${BOOKCLERK_ENV}"
chmod 600 "${BOOKCLERK_ENV}"

bashrc="${HOME}/.bashrc"
marker="# bookclerk-devcontainer-git-signing"
if [[ -f "${bashrc}" ]] && ! grep -qF "${marker}" "${bashrc}"; then
  {
    echo ""
    echo "${marker}"
    echo "[[ -f \"${BOOKCLERK_ENV}\" ]] && . \"${BOOKCLERK_ENV}\""
  } >>"${bashrc}"
fi

# Include overlay without replacing the host-copied ~/.gitconfig.
if ! git config --global --get-all include.path 2>/dev/null | grep -qxF "${BOOKCLERK_GITCONFIG}"; then
  git config --global --add include.path "${BOOKCLERK_GITCONFIG}"
fi

existing_format="$(git config --get gpg.format 2>/dev/null || true)"
existing_gpgsign="$(git config --get commit.gpgsign 2>/dev/null || true)"
existing_key="$(git config --get user.signingkey 2>/dev/null || true)"

# Build overlay. Host gitconfig wins unless we must fix a container hazard or
# an explicit env override was provided.
{
  echo "# Generated by .devcontainer/git-signing.sh — Dev Container overlay only."
  echo "# Configure identity/signing on the host with git config (typical setup)."

  # Optional identity overrides (env → git config). Empty localEnv is ignored.
  name="${GIT_AUTHOR_NAME:-${GIT_COMMITTER_NAME:-}}"
  email="${GIT_AUTHOR_EMAIL:-${GIT_COMMITTER_EMAIL:-}}"
  if [[ -n "${name}" || -n "${email}" || -n "${GIT_SSH_SIGNING_PUBKEY:-}" ]]; then
    echo "[user]"
    [[ -n "${name}" ]] && printf '\tname = %s\n' "${name}"
    [[ -n "${email}" ]] && printf '\temail = %s\n' "${email}"
    if [[ -n "${GIT_SSH_SIGNING_PUBKEY:-}" ]]; then
      pubkey="${GIT_SSH_SIGNING_PUBKEY}"
      [[ "${pubkey}" == key::* ]] || pubkey="key::${pubkey}"
      printf '\tsigningKey = %s\n' "${pubkey}"
    fi
  fi

  if [[ -n "${GIT_SSH_SIGNING_PUBKEY:-}" ]]; then
    echo "[gpg]"
    echo -e "\tformat = ssh"
    echo "[commit]"
    echo -e "\tgpgsign = true"
    signing_desc="env:GIT_SSH_SIGNING_PUBKEY"
  elif [[ -n "${existing_key}" && "${existing_key}" != key::* && ! -e "${existing_key}" ]]; then
    # Host path like ~/.ssh/id_ed25519.pub is missing in the container.
    echo "[gpg]"
    echo -e "\tformat = ssh"
    echo "[gpg \"ssh\"]"
    echo -e "\tdefaultKeyCommand = ssh-add -L"
    echo "[commit]"
    echo -e "\tgpgsign = true"
    signing_desc="agent:defaultKeyCommand (host signingKey path missing)"
  elif [[ "${existing_format}" == ssh || "${existing_gpgsign}" == true || "${existing_gpgsign}" == yes ]]; then
    # Host already configured signing; keep it. Only add defaultKeyCommand if
    # there is no usable signingKey.
    if [[ -z "${existing_key}" ]]; then
      echo "[gpg \"ssh\"]"
      echo -e "\tdefaultKeyCommand = ssh-add -L"
      signing_desc="host-gitconfig + agent defaultKeyCommand"
    else
      signing_desc="host-gitconfig (unchanged)"
    fi
  else
    echo "[gpg]"
    echo -e "\tformat = ssh"
    echo "[gpg \"ssh\"]"
    echo -e "\tdefaultKeyCommand = ssh-add -L"
    echo "[commit]"
    echo -e "\tgpgsign = true"
    signing_desc="agent:defaultKeyCommand"
  fi
} >"${BOOKCLERK_GITCONFIG}"
chmod 600 "${BOOKCLERK_GITCONFIG}"

log "ready (sock=${SSH_AUTH_SOCK}; ${signing_desc}; overlay=${BOOKCLERK_GITCONFIG})"
