#!/usr/bin/env bash
# Configure SSH commit signing for the Dev Container from runtime env vars.
#
# No-op when signing material is unset (keys can be provided later).
#
# Identity (git-native env overrides — no config file required):
#   GIT_AUTHOR_NAME / GIT_AUTHOR_EMAIL
#   GIT_COMMITTER_NAME / GIT_COMMITTER_EMAIL  (fall back to author if unset)
#
# Signing material (one of):
#   GIT_SSH_SIGNING_KEY       — OpenSSH private key contents (PEM / openssh)
#   GIT_SSH_SIGNING_KEY_FILE  — path to an existing private key file
#
# Optional:
#   GIT_SSH_SIGNING_PUBKEY    — OpenSSH public key line (otherwise derived)
#
# Also exports GIT_CONFIG_* pairs into ~/.config/bookclerk/git-signing.env so
# non-login shells can `source` the same overrides git documents for
# GIT_CONFIG_COUNT / GIT_CONFIG_KEY_n / GIT_CONFIG_VALUE_n.
set -euo pipefail

if [[ -z "${GIT_SSH_SIGNING_KEY:-}" && -z "${GIT_SSH_SIGNING_KEY_FILE:-}" ]]; then
  echo "devcontainer git-signing: no GIT_SSH_SIGNING_KEY(_FILE); leaving unsigned"
  exit 0
fi

mkdir -p "${HOME}/.ssh" "${HOME}/.config/bookclerk"
chmod 700 "${HOME}/.ssh"

key_path="${GIT_SSH_SIGNING_KEY_FILE:-${HOME}/.ssh/bookclerk_commit_signing}"

if [[ -n "${GIT_SSH_SIGNING_KEY:-}" ]]; then
  # Normalize escaped newlines from some secret stores.
  printf '%s\n' "${GIT_SSH_SIGNING_KEY//$'\\n'/$'\n'}" >"${key_path}"
  chmod 600 "${key_path}"
fi

if [[ ! -f "${key_path}" ]]; then
  echo "devcontainer git-signing: missing private key at ${key_path}" >&2
  exit 1
fi
chmod 600 "${key_path}"

pub_path="${key_path}.pub"
if [[ -n "${GIT_SSH_SIGNING_PUBKEY:-}" ]]; then
  printf '%s\n' "${GIT_SSH_SIGNING_PUBKEY}" >"${pub_path}"
else
  ssh-keygen -y -f "${key_path}" >"${pub_path}"
fi
chmod 644 "${pub_path}"

author_name="${GIT_AUTHOR_NAME:-${GIT_COMMITTER_NAME:-}}"
author_email="${GIT_AUTHOR_EMAIL:-${GIT_COMMITTER_EMAIL:-}}"
if [[ -n "${author_name}" && -z "${GIT_COMMITTER_NAME:-}" ]]; then
  export GIT_COMMITTER_NAME="${author_name}"
fi
if [[ -n "${author_email}" && -z "${GIT_COMMITTER_EMAIL:-}" ]]; then
  export GIT_COMMITTER_EMAIL="${author_email}"
fi
if [[ -n "${author_name}" && -z "${GIT_AUTHOR_NAME:-}" ]]; then
  export GIT_AUTHOR_NAME="${author_name}"
fi
if [[ -n "${author_email}" && -z "${GIT_AUTHOR_EMAIL:-}" ]]; then
  export GIT_AUTHOR_EMAIL="${author_email}"
fi

# Persist for IDE / interactive git (env alone is enough for subprocesses that
# inherit remoteEnv; global config covers tools that do not).
git config --global gpg.format ssh
git config --global user.signingkey "${pub_path}"
git config --global commit.gpgsign true
if [[ -n "${author_name}" ]]; then
  git config --global user.name "${author_name}"
fi
if [[ -n "${author_email}" ]]; then
  git config --global user.email "${author_email}"
fi

env_file="${HOME}/.config/bookclerk/git-signing.env"
{
  echo "# Generated by .devcontainer/git-signing.sh — safe to delete."
  echo "export GIT_CONFIG_COUNT=3"
  echo "export GIT_CONFIG_KEY_0=gpg.format"
  echo "export GIT_CONFIG_VALUE_0=ssh"
  echo "export GIT_CONFIG_KEY_1=user.signingkey"
  echo "export GIT_CONFIG_VALUE_1=$(printf '%q' "${pub_path}")"
  echo "export GIT_CONFIG_KEY_2=commit.gpgsign"
  echo "export GIT_CONFIG_VALUE_2=true"
  if [[ -n "${GIT_AUTHOR_NAME:-}" ]]; then
    echo "export GIT_AUTHOR_NAME=$(printf '%q' "${GIT_AUTHOR_NAME}")"
  fi
  if [[ -n "${GIT_AUTHOR_EMAIL:-}" ]]; then
    echo "export GIT_AUTHOR_EMAIL=$(printf '%q' "${GIT_AUTHOR_EMAIL}")"
  fi
  if [[ -n "${GIT_COMMITTER_NAME:-}" ]]; then
    echo "export GIT_COMMITTER_NAME=$(printf '%q' "${GIT_COMMITTER_NAME}")"
  fi
  if [[ -n "${GIT_COMMITTER_EMAIL:-}" ]]; then
    echo "export GIT_COMMITTER_EMAIL=$(printf '%q' "${GIT_COMMITTER_EMAIL}")"
  fi
} >"${env_file}"
chmod 600 "${env_file}"

bashrc="${HOME}/.bashrc"
marker="# bookclerk-devcontainer-git-signing"
if [[ -f "${bashrc}" ]] && ! grep -qF "${marker}" "${bashrc}"; then
  {
    echo ""
    echo "${marker}"
    echo "[[ -f \"\${HOME}/.config/bookclerk/git-signing.env\" ]] && . \"\${HOME}/.config/bookclerk/git-signing.env\""
  } >>"${bashrc}"
fi

echo "devcontainer git-signing: SSH signing configured (key=${pub_path})"
