#!/usr/bin/env python3
"""Generate SDK projections from the plugin ABI source of truth.

Single source of truth: ``crates/bookclerk-plugin-abi/schema/plugin.capnp`` —
product constants, database enums, the Cap'n Proto RPC surface, and the
"JSON payload contracts" section (schemas + docs for the JSON payloads that
travel inside ``Text`` fields such as ``describe().metadataJson`` and role
``paramsJson``). Rust consumes the schema via capnpc codegen plus hand-written
serde types that are drift-checked here; TS / Python projections are fully
generated by ``scripts/sdk_emitters.py``.

``--write`` (re)generates:

- ``packages/plugin-sdk/src/abi.ts`` and ``src/generated.ts``
- ``packages/plugin-sdk-python/.../_abi.py`` and ``.../abi.py``
- constant / error-code lines in ``packages/plugin-sdk/embed/bookclerk_plugin.js``
- the byte-identical embed mirror ``crates/bookclerk-plugin-sdk/embed/bookclerk_plugin.js``
- the ``plugin-toml.json`` copy in the abi crate (mirrors the manifest crate)

``--check`` (default) regenerates in memory and fails on any byte drift, plus:

- Rust serde DTOs in ``types.rs`` / ``kind.rs`` match the JSON payload structs
  declared in the schema (field wire names)
- Rust ``PluginErrorCode`` wire strings match the schema enum
- Rust ``DbPlanStatementKind`` matches the Cap'n Proto enum
- every Cap'n Proto ``ContentSource`` / ``Integration`` method has a
  ``methods.rs`` NAME constant (consent / capability vocabulary)
- fixtures/wire/*.json object keys are camelCase (no `_` in keys)
- legacy JSON-era database names cannot reappear in public artifacts

Exit 1 on drift when --check (default).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import capnp_schema
import sdk_emitters

ROOT = Path(__file__).resolve().parents[1]
METHODS_RS = ROOT / "crates/bookclerk-plugin-abi/src/methods.rs"
ABI_LIB_RS = ROOT / "crates/bookclerk-plugin-abi/src/lib.rs"
TYPES_RS = ROOT / "crates/bookclerk-plugin-abi/src/types.rs"
KIND_RS = ROOT / "crates/bookclerk-plugin-abi/src/kind.rs"
ERROR_RS = ROOT / "crates/bookclerk-plugin-abi/src/error.rs"
DB_EXECUTE_RS = ROOT / "crates/bookclerk-plugin-abi/src/db_execute.rs"
CAPNP_SCHEMAS = (
    ROOT / "crates/bookclerk-plugin-abi/schema/plugin.capnp",
    ROOT / "crates/bookclerk-plugin-abi/schema/plugin_host.capnp",
)
LAYOUT_JSON = ROOT / "crates/bookclerk-plugin-abi/schema/plugin.layout.json"
TS_GENERATED = ROOT / "packages/plugin-sdk/src/generated.ts"
TS_WIRE = ROOT / "packages/plugin-sdk/src/generated-wire.ts"
TS_ABI = ROOT / "packages/plugin-sdk/src/abi.ts"
TS_DB_EXECUTE = ROOT / "packages/plugin-sdk/src/db-execute.ts"
TS_EMBED = ROOT / "packages/plugin-sdk/embed/bookclerk_plugin.js"
RS_EMBED = ROOT / "crates/bookclerk-plugin-sdk/embed/bookclerk_plugin.js"
PY_ABI = ROOT / "packages/plugin-sdk-python/src/bookclerk_plugin_sdk/abi.py"
PY_WIRE = ROOT / "packages/plugin-sdk-python/src/bookclerk_plugin_sdk/_wire.py"
PY_PRODUCT_ABI = ROOT / "packages/plugin-sdk-python/src/bookclerk_plugin_sdk/_abi.py"
PY_DB_VALUE = ROOT / "packages/plugin-sdk-python/src/bookclerk_plugin_sdk/db_value.py"
PLUGIN_TOML_SCHEMA = ROOT / "crates/bookclerk-plugin-abi/schema/plugin-toml.json"
MANIFEST_SCHEMA = ROOT / "crates/bookclerk-plugin-manifest/schema/plugin-toml.json"
WIRE_FIXTURES = ROOT / "crates/bookclerk-plugin-abi/fixtures/wire"

REQUIRED_WIRE_FIXTURES = (
    "login.request.json",
    "login.result.json",
    "scan.request.json",
    "scan.result.json",
    "fetchTitle.request.json",
)


def layout_json(refresh: bool) -> str:
    """Contents of ``plugin.layout.json``.

    With ``refresh`` the Cap'n Proto compiler is consulted through
    ``tools/abi-layout`` (requires ``capnp`` and a warm ``cargo``); otherwise
    the committed document is used and cross-checked against the parsed
    schema by ``sdk_emitters.layout_errors``.
    """
    if not refresh:
        if not LAYOUT_JSON.is_file():
            raise SystemExit(
                f"missing {LAYOUT_JSON.relative_to(ROOT)}; run with --refresh-layout"
            )
        return LAYOUT_JSON.read_text(encoding="utf-8")
    proc = subprocess.run(
        ["cargo", "run", "-q", "-p", "abi-layout", "--", "--schema-dir", str(LAYOUT_JSON.parent)],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(f"abi-layout failed:\n{proc.stderr}")
    return proc.stdout


def check_schema_docs() -> list[str]:
    """Every declaration in plugin.capnp carries a doc comment."""
    schema = capnp_schema.parse_schema(CAPNP_SCHEMAS[0].read_text(encoding="utf-8"))
    return [f"plugin.capnp:{m}: missing doc comment" for m in capnp_schema.missing_docs(schema)]


def check_layout(layout_text: str) -> list[str]:
    """The layout document describes exactly the parsed schema."""
    capnp_text = CAPNP_SCHEMAS[0].read_text(encoding="utf-8")
    layout = sdk_emitters.Layout(json.loads(layout_text))
    return sdk_emitters.layout_errors(capnp_schema.parse_schema(capnp_text), layout)


def generated_targets(layout_text: str) -> dict[Path, str]:
    """Expected contents for every generated SDK artifact, keyed by path."""
    capnp_text = CAPNP_SCHEMAS[0].read_text(encoding="utf-8")
    embed_text = TS_EMBED.read_text(encoding="utf-8")
    synced_embed = sdk_emitters.sync_embed_constants(embed_text, capnp_text)
    layout = sdk_emitters.Layout(json.loads(layout_text))
    return {
        LAYOUT_JSON: layout_text,
        TS_ABI: sdk_emitters.emit_ts_abi(capnp_text),
        TS_GENERATED: sdk_emitters.emit_ts_generated(capnp_text),
        TS_WIRE: sdk_emitters.emit_ts_wire(capnp_text, layout),
        PY_PRODUCT_ABI: sdk_emitters.emit_py_product_abi(capnp_text),
        PY_ABI: sdk_emitters.emit_py_abi(capnp_text),
        PY_WIRE: sdk_emitters.emit_py_wire(capnp_text, layout),
        TS_EMBED: synced_embed,
        # The Rust SDK ships a byte-identical embed mirror via include_str!.
        RS_EMBED: synced_embed,
        PLUGIN_TOML_SCHEMA: MANIFEST_SCHEMA.read_text(encoding="utf-8"),
    }


def collect_snake_keys(value: Any, path: str = "$") -> list[str]:
    """Return paths of object keys that contain `_` (not camelCase)."""
    bad: list[str] = []
    if isinstance(value, dict):
        for key, child in value.items():
            here = f"{path}.{key}"
            if "_" in key:
                bad.append(here)
            bad.extend(collect_snake_keys(child, here))
    elif isinstance(value, list):
        for i, child in enumerate(value):
            bad.extend(collect_snake_keys(child, f"{path}[{i}]"))
    return bad


def check_wire_fixtures() -> list[str]:
    """Validate golden wire fixtures exist and use camelCase object keys."""
    errors: list[str] = []
    if not WIRE_FIXTURES.is_dir():
        return [f"missing wire fixtures dir: {WIRE_FIXTURES}"]
    present = {p.name for p in WIRE_FIXTURES.glob("*.json")}
    for name in REQUIRED_WIRE_FIXTURES:
        if name not in present:
            errors.append(f"missing required wire fixture: {name}")
    for path in sorted(WIRE_FIXTURES.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"{path.name}: invalid JSON ({exc})")
            continue
        for bad in collect_snake_keys(data):
            errors.append(f"{path.name}: non-camelCase key at {bad}")
        if path.name == "login.request.json" and "pluginDataDir" not in data:
            errors.append(f"{path.name}: expected pluginDataDir")
    return errors


# Legacy host-IR types must not be re-exported from the public plugin ABI crate root.
FORBIDDEN_ABI_LIB_EXPORTS = (
    "DbAtomicRequest",
    "DbAtomicPlan",
    "DbPlanExecResult",
    "DbPlanStatement",
    "StatementDto",
    "QueryResultDto",
    "DB_ATOMIC_SENTINEL",
    "DB_CAPABILITIES_SENTINEL",
    "GuestReceiptPersist",
    "HostExecuteEnvelope",
    "sea_null",
)


def check_abi_lib_exports() -> list[str]:
    """Fail when removed legacy database DTOs reappear in lib.rs `pub use`."""
    text = ABI_LIB_RS.read_text(encoding="utf-8")
    # `#[cfg(feature = "host")]`-gated re-exports are host-private surface,
    # invisible to plugin authors on default features — not public ABI.
    text = re.sub(r'#\[cfg\(feature = "host"\)\]\s*\npub use [^;]*;', "", text)
    errors: list[str] = []
    for name in FORBIDDEN_ABI_LIB_EXPORTS:
        if re.search(rf"\bpub use\b[^;]*\b{name}\b", text):
            errors.append(f"lib.rs must not publicly export legacy `{name}`")
        if re.search(rf"^\s*pub use db::\{{[^}}]*\b{name}\b", text, re.MULTILINE):
            errors.append(f"lib.rs must not publicly export legacy `{name}` from db::")
    if "from_atomic" in text or "into_plan_exec" in text:
        errors.append("lib.rs must not document legacy ExecuteRequest bridges")
    return errors


def statement_kinds_rust() -> list[str]:
    """Wire names of `DbPlanStatementKind` variants (camelCase serde)."""
    text = DB_EXECUTE_RS.read_text(encoding="utf-8")
    match = re.search(r"pub enum DbPlanStatementKind \{(.*?)\n\}", text, re.DOTALL)
    if not match:
        raise SystemExit(f"DbPlanStatementKind not found in {DB_EXECUTE_RS}")
    variants = re.findall(r"^\s{4}([A-Z][A-Za-z0-9]*),", match.group(1), re.MULTILINE)
    return [v[0].lower() + v[1:] for v in variants]


def check_statement_kinds() -> list[str]:
    """Rust `DbPlanStatementKind` must match the Cap'n Proto enum, in order.

    TS / Python ordinal tables are generated from the Cap'n schema (see
    `generated_targets`), so only the hand-written Rust enum can drift.
    """
    capnp_text = CAPNP_SCHEMAS[0].read_text(encoding="utf-8")
    rust = statement_kinds_rust()
    capnp = sdk_emitters.parse_capnp_enum(capnp_text, "DbStatementKind")
    errors: list[str] = []
    if capnp != rust:
        errors.append(f"statement kinds drift rust={rust} capnp={capnp}")
    for label, kinds in (("rust", rust), ("capnp", capnp)):
        if "query" in kinds:
            errors.append(f'legacy "query" statement kind must not reappear in {label}')
    return errors


def _camel(snake: str) -> str:
    head, *tail = snake.split("_")
    return head + "".join(part.capitalize() for part in tail)


def rust_struct_wire_fields(name: str) -> list[str] | None:
    """CamelCase wire field names of one serde struct in types.rs / kind.rs."""
    for path in (TYPES_RS, KIND_RS):
        text = path.read_text(encoding="utf-8")
        match = re.search(rf"pub struct {name} \{{(.*?)\n\}}", text, re.DOTALL)
        if not match:
            continue
        fields = re.findall(r"^\s{4}pub (\w+):", match.group(1), re.MULTILINE)
        return [_camel(f) for f in fields]
    return None


def json_payload_decls(schema: capnp_schema.Schema) -> list[capnp_schema.Decl]:
    """Declarations inside the schema's JSON payload contracts section."""
    names = sdk_emitters.json_payload_names(CAPNP_SCHEMAS[0].read_text(encoding="utf-8"))
    return [d for d in schema.decls if d.name in names]


def check_rust_dto_drift() -> list[str]:
    """Rust serde DTOs must match the schema's JSON payload structs."""
    capnp_text = CAPNP_SCHEMAS[0].read_text(encoding="utf-8")
    schema = capnp_schema.parse_schema(capnp_text)
    errors: list[str] = []
    for decl in json_payload_decls(schema):
        if isinstance(decl, capnp_schema.Alias):
            found = False
            for path in (TYPES_RS, KIND_RS):
                if re.search(
                    rf"pub type {decl.name} = {decl.target};",
                    path.read_text(encoding="utf-8"),
                ):
                    found = True
            if not found:
                errors.append(
                    f"missing Rust alias `pub type {decl.name} = {decl.target};`"
                )
            continue
        if not isinstance(decl, capnp_schema.Struct):
            continue
        rust_fields = rust_struct_wire_fields(decl.name)
        if rust_fields is None:
            rust_fields = rust_struct_wire_fields(decl.name + "Dto")
        if rust_fields is None:
            errors.append(f"no Rust serde struct found for schema DTO `{decl.name}`")
            continue
        schema_fields = [f.name for f in decl.fields]
        if sorted(rust_fields) != sorted(schema_fields):
            errors.append(
                f"DTO field drift `{decl.name}`: "
                f"schema-only={sorted(set(schema_fields) - set(rust_fields))} "
                f"rust-only={sorted(set(rust_fields) - set(schema_fields))}"
            )
    return errors


def check_error_codes() -> list[str]:
    """Rust `PluginErrorCode::as_str` values must match the schema enum."""
    capnp_text = CAPNP_SCHEMAS[0].read_text(encoding="utf-8")
    schema_codes = [
        sdk_emitters.snake_wire(e)
        for e in sdk_emitters.parse_capnp_enum(capnp_text, "PluginErrorCode")
    ]
    text = ERROR_RS.read_text(encoding="utf-8")
    rust_codes = re.findall(r'Self::\w+ => "([a-z_]+)"', text)
    # `unknown` is the local catch-all for unrecognized wire codes, not a code
    # a guest may emit — exclude it from the wire vocabulary comparison.
    rust_wire = [c for c in rust_codes if c != "unknown"]
    errors: list[str] = []
    if sorted(set(rust_wire)) != sorted(set(schema_codes)):
        errors.append(
            f"PluginErrorCode drift: schema={sorted(schema_codes)} rust={sorted(set(rust_wire))}"
        )
    return errors


def check_method_names() -> list[str]:
    """Every schema role method needs a methods.rs NAME constant."""
    capnp_text = CAPNP_SCHEMAS[0].read_text(encoding="utf-8")
    methods_text = METHODS_RS.read_text(encoding="utf-8")
    rust_names = set(re.findall(r'pub const NAME: &str = "([^"]+)";', methods_text))
    errors: list[str] = []
    for interface in ("ContentSource", "Integration"):
        match = re.search(rf"interface {interface} \{{(.*?)\n\}}", capnp_text, re.DOTALL)
        if not match:
            errors.append(f"interface {interface} not found in plugin.capnp")
            continue
        for method in re.findall(r"^\s{2}(\w+) @\d+ ", match.group(1), re.MULTILINE):
            if method not in rust_names:
                errors.append(
                    f"schema method `{interface}.{method}` missing from methods.rs"
                )
    for legacy in ("handshake", "credentialsUpdate", "putFile", "touchFile", "probe"):
        if legacy in rust_names:
            errors.append(f"legacy method name `{legacy}` must not reappear in methods.rs")
    return errors


# JSON-era database RPC names, DTOs, and handshake-era transport types deleted
# from the public ABI; none may reappear in schemas or generated SDK sources.
LEGACY_TOKENS = (
    "StatementDto",
    "QueryResultDto",
    "valuesJson",
    "rowsJson",
    "dbConnect",
    "dbQuery",
    "dbExecute",
    "dbBegin",
    "dbCommit",
    "dbRollback",
    "dbAtomic",
    "DbConnectResult",
    "DbConnectParams",
    "HandshakeParams",
    "HandshakeResult",
    "RpcRequest",
    "RpcResponse",
    "abiMajor",
    "abiMinor",
    "envelopeVersion",
    "executeEnvelope",
    "migration_plan",
)


def check_legacy_tokens() -> list[str]:
    """Fail when deleted JSON-era names reappear in public artifacts."""
    targets = (
        *CAPNP_SCHEMAS,
        TS_GENERATED,
        TS_ABI,
        TS_DB_EXECUTE,
        PY_ABI,
        PY_PRODUCT_ABI,
        PY_DB_VALUE,
    )
    errors: list[str] = []
    for path in targets:
        if not path.is_file():
            errors.append(f"missing legacy-token scan target: {path}")
            continue
        text = path.read_text(encoding="utf-8")
        for token in LEGACY_TOKENS:
            if re.search(rf"\b{token}\b", text):
                errors.append(
                    f"{path.relative_to(ROOT)}: legacy `{token}` must not reappear"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--refresh-layout",
        action="store_true",
        help="re-derive plugin.layout.json via `cargo run -p abi-layout` (needs capnp)",
    )
    args = parser.parse_args()
    if not args.write:
        args.check = True

    layout_text = layout_json(refresh=args.refresh_layout)
    layout_problems = check_layout(layout_text)
    if layout_problems:
        for err in layout_problems:
            print(f"layout: {err}", file=sys.stderr)
        print(
            "plugin.layout.json does not match plugin.capnp "
            "(run scripts/gen-plugin-abi.py --write --refresh-layout)",
            file=sys.stderr,
        )
        return 1

    drift = False
    targets = generated_targets(layout_text)
    for path, expected in targets.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current == expected:
            continue
        if args.write:
            path.write_text(expected, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
        else:
            print(
                f"generated artifact drift: {path.relative_to(ROOT)} "
                "(run scripts/gen-plugin-abi.py --write)",
                file=sys.stderr,
            )
            drift = True

    # The remaining checks are not auto-fixable; fail even under `--write`.
    check_errors: list[str] = []
    for label, check in (
        ("schema docs", check_schema_docs),
        ("wire fixtures", check_wire_fixtures),
        ("abi exports", check_abi_lib_exports),
        ("statement kinds", check_statement_kinds),
        ("rust dto drift", check_rust_dto_drift),
        ("error codes", check_error_codes),
        ("method names", check_method_names),
        ("legacy names", check_legacy_tokens),
    ):
        for err in check():
            print(f"{label}: {err}", file=sys.stderr)
            check_errors.append(err)

    if check_errors:
        return 1
    if drift and args.check and not args.write:
        return 1
    capnp_text = CAPNP_SCHEMAS[0].read_text(encoding="utf-8")
    schema = capnp_schema.parse_schema(capnp_text)
    print(
        f"ok generated={len(targets)} structs={len(schema.structs)} "
        f"interfaces={len(schema.interfaces)} json_dtos={len(json_payload_decls(schema))} "
        f"wire_fixtures={len(REQUIRED_WIRE_FIXTURES)} "
        f"abi_export_guard={len(FORBIDDEN_ABI_LIB_EXPORTS)} "
        f"statement_kinds={len(statement_kinds_rust())} "
        f"legacy_name_guard={len(LEGACY_TOKENS)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
