#!/usr/bin/env python3
"""Sync derived workerd pin + bridge copies from crates/bookclerk-workerd.

Source of truth:
  - crates/bookclerk-workerd/workerd-pin.json
  - crates/bookclerk-workerd/bridge/*.js

Derived:
  - crates/bookclerk-workerd/src/pin.rs (const API + include_str check)
  - packages/plugin-sdk/workerd-pin.json
  - packages/plugin-sdk-python/workerd-pin.json
  - packages/plugin-sdk-python/src/bookclerk_plugin_sdk/workerd-pin.json
  - packages/plugin-sdk/bridge/{bridge,egress,host_stub}.js
  - packages/plugin-sdk-python/src/bookclerk_plugin_sdk/bridge/{…}.js

Exit codes:
  0 — ok (wrote, or --check clean)
  1 — error / drift under --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PIN_JSON = ROOT / "crates/bookclerk-workerd/workerd-pin.json"
PIN_RS = ROOT / "crates/bookclerk-workerd/src/pin.rs"
STUB_COPIES = (
    ROOT / "packages/plugin-sdk/workerd-pin.json",
    ROOT / "packages/plugin-sdk-python/workerd-pin.json",
    ROOT / "packages/plugin-sdk-python/src/bookclerk_plugin_sdk/workerd-pin.json",
)

BRIDGE_SRC = ROOT / "crates/bookclerk-workerd/bridge"
BRIDGE_FILES = ("bridge.js", "egress.js", "host_stub.js")
BRIDGE_DESTS = (
    ROOT / "packages/plugin-sdk/bridge",
    ROOT / "packages/plugin-sdk-python/src/bookclerk_plugin_sdk/bridge",
)

# Stable platform key order for generated Rust match arms.
PLATFORM_ORDER = (
    "linux-x86_64",
    "linux-aarch64",
    "macos-x86_64",
    "macos-aarch64",
    "windows-x86_64",
)

# platform key → (std::env::consts::OS, ARCH)
PLATFORM_MATCH: dict[str, tuple[str, str]] = {
    "linux-x86_64": ("linux", "x86_64"),
    "linux-aarch64": ("linux", "aarch64"),
    "macos-x86_64": ("macos", "x86_64"),
    "macos-aarch64": ("macos", "aarch64"),
    "windows-x86_64": ("windows", "x86_64"),
}

DEFAULT_COOLDOWN_DAYS = 7


def load_pin(path: Path = PIN_JSON) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    validate_pin(data, path)
    return data


def validate_pin(data: object, path: Path) -> None:
    if not isinstance(data, dict):
        raise SystemExit(f"{path}: expected object")
    for key in ("release_tag", "bundled_compat_date", "version_stamp", "assets"):
        if key not in data:
            raise SystemExit(f"{path}: missing {key!r}")
    assets = data["assets"]
    if not isinstance(assets, dict):
        raise SystemExit(f"{path}: assets must be an object")
    missing = [k for k in PLATFORM_ORDER if k not in assets]
    if missing:
        raise SystemExit(f"{path}: assets missing platforms {missing}")
    for key in PLATFORM_ORDER:
        entry = assets[key]
        if not isinstance(entry, dict):
            raise SystemExit(f"{path}: assets[{key!r}] must be an object")
        for field in ("artifact", "sha256_hex"):
            if field not in entry or not isinstance(entry[field], str) or not entry[field]:
                raise SystemExit(f"{path}: assets[{key!r}].{field} required")
        if not re.fullmatch(r"[0-9a-f]{64}", entry["sha256_hex"]):
            raise SystemExit(
                f"{path}: assets[{key!r}].sha256_hex must be 64 lowercase hex chars"
            )


def canonical_json(data: dict) -> str:
    """Pretty JSON with stable key order matching PLATFORM_ORDER for assets."""
    ordered_assets = {
        key: {
            "artifact": data["assets"][key]["artifact"],
            "sha256_hex": data["assets"][key]["sha256_hex"],
        }
        for key in PLATFORM_ORDER
    }
    payload = {
        "release_tag": data["release_tag"],
        "bundled_compat_date": data["bundled_compat_date"],
        "version_stamp": data["version_stamp"],
        "assets": ordered_assets,
    }
    return json.dumps(payload, indent=2) + "\n"


def render_pin_rs(data: dict) -> str:
    tag = data["release_tag"]
    compat = data["bundled_compat_date"]
    stamp = data["version_stamp"]
    arms: list[str] = []
    checks: list[str] = []
    for key in PLATFORM_ORDER:
        os_name, arch = PLATFORM_MATCH[key]
        asset = data["assets"][key]
        arms.append(
            f'''        ("{os_name}", "{arch}") => Some(WorkerdAsset {{
            artifact: "{asset["artifact"]}",
            sha256_hex: "{asset["sha256_hex"]}",
        }}),'''
        )
        checks.append(
            f'''            (
                "{key}",
                "{os_name}",
                "{arch}",
                asset_for_target("{os_name}", "{arch}").expect("{key}"),
            ),'''
        )
    match_arms = "\n".join(arms)
    platform_checks = "\n".join(checks)
    return f'''//! Pinned Cloudflare `workerd` release metadata shared with `bookclerk-dev`.
//!
//! Source of truth: `../workerd-pin.json` (do not edit this file by hand).
//! Bumped by `scripts/bump-workerd-pin.py` (CI: `.github/workflows/workerd-pin-bump.yml`)
//! with a {DEFAULT_COOLDOWN_DAYS}-day publish cooldown for supply-chain safety.
//! Regenerated by `scripts/sync-workerd-pin.py`.

/// Canonical pin JSON (`crates/bookclerk-workerd/workerd-pin.json`).
/// Embedded so a missing/moved SoT fails the build; compared in unit tests.
#[cfg(test)]
const WORKERD_PIN_JSON: &str = include_str!("../workerd-pin.json");

#[cfg(not(test))]
const _: &str = include_str!("../workerd-pin.json");

/// Newest compatibility date this Bookclerk build claims to understand.
pub const BUNDLED_WORKERD_COMPAT_DATE: &str = "{compat}";

/// GitHub release tag (includes leading `v`).
pub const WORKERD_RELEASE_TAG: &str = "{tag}";

/// Filename written beside the binary so ensure can skip re-downloads.
pub const WORKERD_VERSION_STAMP: &str = "{stamp}";

/// GitHub release asset name + sha256 (hex) of the `.gz` payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorkerdAsset {{
    /// Cloudflare release asset filename (for example `workerd-linux-64.gz`).
    pub artifact: &'static str,
    /// Expected SHA-256 hex digest of the gzipped download bytes.
    pub sha256_hex: &'static str,
}}

/// Look up the pinned download asset for a `std::env::consts` OS/arch pair.
///
/// # Arguments
///
/// * `os` - Host OS string (`linux`, `macos`, or `windows`).
/// * `arch` - Host CPU string (`x86_64` or `aarch64`).
///
/// # Returns
///
/// [`WorkerdAsset`] when the pin JSON lists that target; otherwise `None`.
#[must_use]
pub fn asset_for_target(os: &str, arch: &str) -> Option<WorkerdAsset> {{
    match (os, arch) {{
{match_arms}
        _ => None,
    }}
}}

/// Resolve the release asset for the compiling host OS/arch.
#[must_use]
pub fn host_asset() -> Option<WorkerdAsset> {{
    asset_for_target(std::env::consts::OS, std::env::consts::ARCH)
}}

/// Build the GitHub release download URL for a pinned artifact name.
///
/// # Arguments
///
/// * `artifact` - Release asset filename from [`WorkerdAsset::artifact`].
///
/// # Returns
///
/// Absolute `https://github.com/cloudflare/workerd/releases/download/...` URL.
#[must_use]
pub fn download_url(artifact: &str) -> String {{
    format!(
        "https://github.com/cloudflare/workerd/releases/download/{{WORKERD_RELEASE_TAG}}/{{artifact}}"
    )
}}

/// On-disk binary name after extracting the gzipped release asset.
#[must_use]
pub fn binary_name() -> &'static str {{
    if cfg!(windows) {{
        "workerd.exe"
    }} else {{
        "workerd"
    }}
}}

#[cfg(test)]
mod pin_json_sync {{
    use super::*;

    #[test]
    fn pin_rs_constants_match_workerd_pin_json() {{
        let v: serde_json::Value =
            serde_json::from_str(WORKERD_PIN_JSON).expect("workerd-pin.json");
        assert_eq!(
            v["release_tag"].as_str(),
            Some(WORKERD_RELEASE_TAG),
            "WORKERD_RELEASE_TAG drift vs workerd-pin.json"
        );
        assert_eq!(
            v["bundled_compat_date"].as_str(),
            Some(BUNDLED_WORKERD_COMPAT_DATE),
            "BUNDLED_WORKERD_COMPAT_DATE drift vs workerd-pin.json"
        );
        assert_eq!(
            v["version_stamp"].as_str(),
            Some(WORKERD_VERSION_STAMP),
            "WORKERD_VERSION_STAMP drift vs workerd-pin.json"
        );
        let assets = v["assets"].as_object().expect("assets object");
        let platforms = [
{platform_checks}
        ];
        for (key, _os, _arch, got) in platforms {{
            let entry = &assets[key];
            assert_eq!(
                got.artifact,
                entry["artifact"].as_str().unwrap(),
                "{{key}} artifact drift"
            );
            assert_eq!(
                got.sha256_hex,
                entry["sha256_hex"].as_str().unwrap(),
                "{{key}} sha256 drift"
            );
        }}
    }}
}}
'''


def write_bridge_copies() -> list[Path]:
    """Copy bridge JS into SDK trees. Returns paths written/updated."""
    written: list[Path] = []
    if not BRIDGE_SRC.is_dir():
        raise SystemExit(f"missing bridge source dir {BRIDGE_SRC}")
    for dest_dir in BRIDGE_DESTS:
        dest_dir.mkdir(parents=True, exist_ok=True)
        for name in BRIDGE_FILES:
            src = BRIDGE_SRC / name
            if not src.is_file():
                raise SystemExit(f"missing bridge file {src}")
            dest = dest_dir / name
            body = src.read_bytes()
            if not dest.exists() or dest.read_bytes() != body:
                dest.write_bytes(body)
                written.append(dest)
    return written


def check_bridge_copies() -> list[str]:
    """Return drift messages for SDK bridge trees (empty if clean)."""
    errors: list[str] = []
    if not BRIDGE_SRC.is_dir():
        return [f"missing bridge source dir {BRIDGE_SRC.relative_to(ROOT)}"]
    for dest_dir in BRIDGE_DESTS:
        rel_dir = dest_dir.relative_to(ROOT)
        if not dest_dir.is_dir():
            errors.append(f"missing bridge dir {rel_dir}")
            continue
        for name in BRIDGE_FILES:
            src = BRIDGE_SRC / name
            dest = dest_dir / name
            rel = dest.relative_to(ROOT)
            if not src.is_file():
                errors.append(f"missing bridge source {src.relative_to(ROOT)}")
                continue
            if not dest.is_file():
                errors.append(f"missing bridge copy {rel}")
            elif dest.read_bytes() != src.read_bytes():
                errors.append(
                    f"{rel} disagrees with crates/bookclerk-workerd/bridge/{name} "
                    "(run: python3 scripts/sync-workerd-pin.py --write)"
                )
    return errors


def write_derived(data: dict) -> list[Path]:
    """Write pin.rs + stub JSON copies + bridge JS. Returns paths written."""
    written: list[Path] = []
    pin_text = render_pin_rs(data)
    PIN_RS.parent.mkdir(parents=True, exist_ok=True)
    PIN_RS.write_text(pin_text, encoding="utf-8")
    written.append(PIN_RS)

    body = canonical_json(data)
    # Keep SoT canonical too when syncing (stable formatting).
    if PIN_JSON.read_text(encoding="utf-8") != body:
        PIN_JSON.write_text(body, encoding="utf-8")
        written.append(PIN_JSON)

    for stub in STUB_COPIES:
        stub.parent.mkdir(parents=True, exist_ok=True)
        if not stub.exists() or stub.read_text(encoding="utf-8") != body:
            stub.write_text(body, encoding="utf-8")
            written.append(stub)

    written.extend(write_bridge_copies())
    return written


def check_derived(data: dict) -> list[str]:
    """Return human-readable drift messages (empty if clean)."""
    errors: list[str] = []
    expected_rs = render_pin_rs(data)
    if not PIN_RS.is_file():
        errors.append(f"missing {PIN_RS.relative_to(ROOT)}")
    elif PIN_RS.read_text(encoding="utf-8") != expected_rs:
        errors.append(
            f"{PIN_RS.relative_to(ROOT)} disagrees with workerd-pin.json "
            "(run: python3 scripts/sync-workerd-pin.py --write)"
        )

    body = canonical_json(data)
    if PIN_JSON.read_text(encoding="utf-8") != body:
        errors.append(
            f"{PIN_JSON.relative_to(ROOT)} is not in canonical form "
            "(run: python3 scripts/sync-workerd-pin.py --write)"
        )

    for stub in STUB_COPIES:
        rel = stub.relative_to(ROOT)
        if not stub.is_file():
            errors.append(f"missing stub copy {rel}")
        elif stub.read_text(encoding="utf-8") != body:
            errors.append(
                f"{rel} disagrees with workerd-pin.json "
                "(run: python3 scripts/sync-workerd-pin.py --write)"
            )

    errors.extend(check_bridge_copies())
    return errors


def parse_pin_rs_constants(text: str) -> dict[str, str]:
    """Extract the three string consts from pin.rs for a lightweight mismatch report."""
    out: dict[str, str] = {}
    for name in (
        "BUNDLED_WORKERD_COMPAT_DATE",
        "WORKERD_RELEASE_TAG",
        "WORKERD_VERSION_STAMP",
    ):
        m = re.search(rf'pub const {name}:\s*&str\s*=\s*"([^"]+)"', text)
        if m:
            out[name] = m.group(1)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate pin.rs, SDK stub JSON, and bridge JS copies",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if pin.rs, stub copies, or bridge JS disagree with SoT",
    )
    args = parser.parse_args()
    if not args.write and not args.check:
        args.check = True

    data = load_pin()

    if args.write:
        written = write_derived(data)
        if written:
            for path in written:
                print(f"wrote {path.relative_to(ROOT)}")
        else:
            print("already in sync")
        if args.check:
            # After write, verify clean.
            errors = check_derived(load_pin())
            if errors:
                for err in errors:
                    print(err, file=sys.stderr)
                return 1
        return 0

    errors = check_derived(data)
    if PIN_RS.is_file():
        consts = parse_pin_rs_constants(PIN_RS.read_text(encoding="utf-8"))
        mapping = {
            "WORKERD_RELEASE_TAG": data["release_tag"],
            "BUNDLED_WORKERD_COMPAT_DATE": data["bundled_compat_date"],
            "WORKERD_VERSION_STAMP": data["version_stamp"],
        }
        for name, want in mapping.items():
            got = consts.get(name)
            if got is not None and got != want:
                msg = f"pin.rs {name}={got!r} ≠ workerd-pin.json {want!r}"
                if msg not in errors:
                    errors.append(msg)

    if errors:
        for err in errors:
            print(err, file=sys.stderr)
        return 1
    print("workerd pin + bridge sync ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
