//! Pinned Cloudflare `workerd` release metadata shared with `bookclerk-dev`.
//!
//! Source of truth: `../workerd-pin.json` (do not edit this file by hand).
//! Bumped by `scripts/bump-workerd-pin.py` (CI: `.github/workflows/workerd-pin-bump.yml`)
//! with a 7-day publish cooldown for supply-chain safety.
//! Regenerated by `scripts/sync-workerd-pin.py`.

/// Canonical pin JSON (`crates/bookclerk-workerd/workerd-pin.json`).
/// Embedded so a missing/moved SoT fails the build; compared in unit tests.
#[cfg(test)]
const WORKERD_PIN_JSON: &str = include_str!("../workerd-pin.json");

#[cfg(not(test))]
const _: &str = include_str!("../workerd-pin.json");

/// Newest compatibility date this Bookclerk build claims to understand.
pub const BUNDLED_WORKERD_COMPAT_DATE: &str = "2026-09-11";

/// GitHub release tag (includes leading `v`).
pub const WORKERD_RELEASE_TAG: &str = "v1.20260911.1";

/// Filename written beside the binary so ensure can skip re-downloads.
pub const WORKERD_VERSION_STAMP: &str = "workerd.version";

/// GitHub release asset name + sha256 (hex) of the `.gz` payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorkerdAsset {
    /// Cloudflare release asset filename (for example `workerd-linux-64.gz`).
    pub artifact: &'static str,
    /// Expected SHA-256 hex digest of the gzipped download bytes.
    pub sha256_hex: &'static str,
}

/// Look up the pinned download asset for a `std::env::consts` OS/arch pair.
///
/// # Arguments
///
/// * `os` - Host OS string (`linux`, `macos`, or `windows`).
/// * `arch` - Host CPU string (`x86_64` or `aarch64`).
///
/// # Returns
///
/// [`WorkerdAsset`] when the pin JSON lists that target; otherwise `None`.
#[must_use]
pub fn asset_for_target(os: &str, arch: &str) -> Option<WorkerdAsset> {
    match (os, arch) {
        ("linux", "x86_64") => Some(WorkerdAsset {
            artifact: "workerd-linux-64.gz",
            sha256_hex: "5de6114f7982dafd1ceb11fe48df690392b5554454786d355b52844b9b3d7d4e",
        }),
        ("linux", "aarch64") => Some(WorkerdAsset {
            artifact: "workerd-linux-arm64.gz",
            sha256_hex: "d5297c6afc907de0e47c9a8db742b557efc6c97d0e9e7fab129aa5ae4aa1836a",
        }),
        ("macos", "x86_64") => Some(WorkerdAsset {
            artifact: "workerd-darwin-64.gz",
            sha256_hex: "91b510ae03aa9730022f44c9fc8aeb77af5ee295306bb5eef22ab8a63e0e633d",
        }),
        ("macos", "aarch64") => Some(WorkerdAsset {
            artifact: "workerd-darwin-arm64.gz",
            sha256_hex: "640d57e2205be322e1dec6cbc7458ce3d5d31c7a340f7b19ae066e73f2a63343",
        }),
        ("windows", "x86_64") => Some(WorkerdAsset {
            artifact: "workerd-windows-64.gz",
            sha256_hex: "53cf647eabeee3429cfb80ea4fad952977d849c53d337483932792603e51d260",
        }),
        _ => None,
    }
}

/// Resolve the release asset for the compiling host OS/arch.
#[must_use]
pub fn host_asset() -> Option<WorkerdAsset> {
    asset_for_target(std::env::consts::OS, std::env::consts::ARCH)
}

/// Build the GitHub release download URL for a pinned artifact name.
///
/// # Arguments
///
/// * `artifact` - Release asset filename from [`WorkerdAsset::artifact`].
///
/// # Returns
///
/// Absolute `https://github.com/cloudflare/workerd/releases/download/...` URL.
#[must_use]
pub fn download_url(artifact: &str) -> String {
    format!(
        "https://github.com/cloudflare/workerd/releases/download/{WORKERD_RELEASE_TAG}/{artifact}"
    )
}

/// On-disk binary name after extracting the gzipped release asset.
#[must_use]
pub fn binary_name() -> &'static str {
    if cfg!(windows) {
        "workerd.exe"
    } else {
        "workerd"
    }
}

#[cfg(test)]
mod pin_json_sync {
    use super::*;

    #[test]
    fn pin_rs_constants_match_workerd_pin_json() {
        let v: serde_json::Value =
            serde_json::from_str(WORKERD_PIN_JSON).expect("workerd-pin.json");
        assert_eq!(
            v["release_tag"].as_str(),
            Some(WORKERD_RELEASE_TAG),
            "WORKERD_RELEASE_TAG drift vs workerd-pin.json"
        );
        assert_eq!(
            v["bundled_compat_date"].as_str(),
            Some(BUNDLED_WORKERD_COMPAT_DATE),
            "BUNDLED_WORKERD_COMPAT_DATE drift vs workerd-pin.json"
        );
        assert_eq!(
            v["version_stamp"].as_str(),
            Some(WORKERD_VERSION_STAMP),
            "WORKERD_VERSION_STAMP drift vs workerd-pin.json"
        );
        let assets = v["assets"].as_object().expect("assets object");
        let platforms = [
            (
                "linux-x86_64",
                "linux",
                "x86_64",
                asset_for_target("linux", "x86_64").expect("linux-x86_64"),
            ),
            (
                "linux-aarch64",
                "linux",
                "aarch64",
                asset_for_target("linux", "aarch64").expect("linux-aarch64"),
            ),
            (
                "macos-x86_64",
                "macos",
                "x86_64",
                asset_for_target("macos", "x86_64").expect("macos-x86_64"),
            ),
            (
                "macos-aarch64",
                "macos",
                "aarch64",
                asset_for_target("macos", "aarch64").expect("macos-aarch64"),
            ),
            (
                "windows-x86_64",
                "windows",
                "x86_64",
                asset_for_target("windows", "x86_64").expect("windows-x86_64"),
            ),
        ];
        for (key, _os, _arch, got) in platforms {
            let entry = &assets[key];
            assert_eq!(
                got.artifact,
                entry["artifact"].as_str().unwrap(),
                "{key} artifact drift"
            );
            assert_eq!(
                got.sha256_hex,
                entry["sha256_hex"].as_str().unwrap(),
                "{key} sha256 drift"
            );
        }
    }
}
