// Generated by `bookclerk-plugin types` from plugin.toml (id=echo_workerd_ts). Do not edit.
// Regenerate after changing [vars], [secrets], [[events.producers]], [[databases]],
// [work_fs], [[kv_namespaces]], or [oauth].
import type { BookclerkEnv, DatabaseBinding } from "@bookclerk/plugin-sdk/workerd";

/**
 * Bindings the host grants to `echo_workerd_ts`; use as
 * `class Default extends BookclerkEntrypoint<Env>`.
 */
export interface Env extends BookclerkEnv {
  /** `[vars]` plus operator settings decoded from the granted config payload. */
  CONFIG: Record<string, unknown>;
  /** `[[kv_namespaces]]` store (surface reserved). */
  KV: unknown;
  /** `[[databases]]` plugin-owned database (D1-shaped `prepare`/`batch`/`exec`). */
  DB: DatabaseBinding;
}
